---
- hosts: sites
  become: true
  vars:
    ### Role Variables
    # Set this to true if Netbird is installed on the host
    use_netbird: true

  pre_tasks:
    - name: Get CANTACS system info
      include_tasks: tasks/get_cantacs_info.yml

  roles:
    - host_role
